### ISSUE TITLE
关于advance_sz

### ISSUE THREAD

**Issue by ahao1995** [MengRao/PubSubQueue#1]
您好，请教您一个问题：
```
uint32_t blk_sz = toBlk(size);
uint32_t advance_sz = blk_sz + (rewind ? padding_sz : 0);
if(advance_sz > BLK_CNT) { // msg size too large
    return nullptr;
}
```
在判断msg_size时，为何使用advance_sz进行比较，而不是使用blk_sz ，每次rewind后会加上padding，应该是相当于从头开始写，那只要消息体占用的小于总的数量就可了，这个比较这里不知是不是bug，或者有其他考虑

**Comment by MengRao** [comment]
rewind时padding_sz是浪费掉的，但是不能立即写新msg，而是用来要告诉reader发生rewind了，下一个msg要从头开始。这是通过`blk[written_idx % BLK_CNT].header.size = 0;`做到的。

**Comment by ahao1995** [comment]
非常感谢！！！
