### ISSUE TITLE
queue delay issue

### ISSUE THREAD

**Issue by yangqun** [MengRao/PubSubQueue#2]
Hello, I changed pub.cc and sub.cc's time function to now() in timestamp.h, and nothing else changed.
after compilation  it.s latency output is about 4000us, is there any problems with it ?
![image](https://user-images.githubusercontent.com/5195784/149808972-6b8229b0-e2a8-4db4-ac0d-06e865b44ae7.png)

**Comment by MengRao** [comment]
![image](https://user-images.githubusercontent.com/11496526/149852741-86ee9d6f-a2cb-4de5-aba9-7568e84b6b02.png)
我测试的结果是正常的，有可能你的机器cpu负载较高。

**Comment by ahao1995** [comment]
我发现了另一个问题
typedef Msg<1, 1> Msg1;
typedef Msg<31, 2> Msg2;
typedef Msg<62, 3> Msg3;
typedef Msg<125, 4> Msg4;
我将参数改成上述参数，发现每隔几秒会发生十倍以上的抖动，，单独发送一种msg也会发生这种情况，会产生几倍的跳动，不知道是什么原因，您可以给些排查意见么

**Comment by yangqun** [comment]
![image](https://user-images.githubusercontent.com/5195784/149855071-ed67f0b0-8aeb-494f-9fdc-9d7500d2848b.png)
确实是服务器负载比较大造成的。我换了一台服务器基本在1us左右。谢谢

**Comment by MengRao** [comment]
> 我发现了另一个问题 typedef Msg<1, 1> Msg1; typedef Msg<31, 2> Msg2; typedef Msg<62, 3> Msg3; typedef Msg<125, 4> Msg4; 我将参数改成上述参数，发现每隔几秒会发生十倍以上的抖动，，单独发送一种msg也会发生这种情况，会产生几倍的跳动，不知道是什么原因，您可以给些排查意见么

常规的系统延迟抖动吧，先做下低延迟相关的系统设置再试。
